language: generic
services:
  - docker

before_install:
  - docker build -t mittalvaibhav1/docker-react-cicd -f Dockerfile.dev .

script:
  - docker run -e CI=true mittalvaibhav1/docker-react-cicd npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  env: Dockerreactcicd-env
  app: docker-react-cicd
  bucket_name: "elasticbeanstalk-us-east-1-000760942121"
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY  